# Generated by Django 4.2.2 on 2023-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlisting_bids_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
