# Generated by Django 4.2.2 on 2023-06-16 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auctionlisting_isactive_auctionlisting_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bids",
            new_name="Bid",
        ),
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
