# Generated by Django 4.2.2 on 2023-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_user_bid_value_comment_user_comment_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.auctionlisting",
            ),
        ),
    ]
