# Generated by Django 4.2.2 on 2023-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_bid_listing_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to="auctions.auctionlisting"
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Broom", "Broom"),
                    ("Cloak", "Cloak"),
                    ("Book", "Book"),
                    ("Wand", "Wand"),
                    ("Quill", "Quill"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="value",
            field=models.CharField(max_length=64),
        ),
    ]
