# Generated by Django 4.2.2 on 2023-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_user_watchlist_alter_auctionlisting_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Broomstick", "Broomstick"),
                    ("Cloak", "Cloak"),
                    ("Book", "Book"),
                    ("Wand", "Wand"),
                    ("Quill", "Quill"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="value",
            field=models.CharField(max_length=256),
        ),
    ]
