# Generated by Django 4.2.2 on 2023-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_auctionlisting_category_alter_comment_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Broomstick", "Broomstick"),
                    ("Robe", "Robe"),
                    ("Book", "Book"),
                    ("Wand", "Wand"),
                    ("Quill", "Quill"),
                ],
                max_length=32,
            ),
        ),
    ]
